### ISSUE TITLE
Hey no offense but it's *really* time wasting.

### ISSUE THREAD

**Issue by Subilan** [AmarokIce/TskimiSeiranFruitWine#2]
I'm trying to launch a modded server with over 100 mods, but ended up constantly facing a weird problem: while the server and client both run well, no one can join the server as there is something wrong.

So what is the problem? It bumped out the message on player's join that `*something* NullPointerException *something* "p_130086_" is null *something*` or whatever. This is pretty absurd to me. So I googled it and found that no one could escape the fate that they have to do *dichotomy* with their massive mod list to find a single mod causing the problem.

Pretty sad.

Then guess what. This mod is one of the causing mods. And there are still a lot out there. Somehow I think it's **quite necessary** to build a list for all of the mods that are breaking some *Rule of the Heaven* which could make helpless mod server owners spend their nights being confused and surrender to the fate of "Tired or Quit".

**Comment by Subilan** [comment]
According to the Internet this is caused by some mistake or conflict in applying recipes. I don't know the details and hopefully you can look into it.

Nice mod, I have to say, since many of my players have chosen this as their favorite mods. I'll give you a star.

**Comment by AmarokIce** [comment]
Another player report this, it had something wrongs with Tinkers' Construct 3, I'm didn't know what it happend but I will try to fix it
And thank you report this! I'm sorry for this issues

**Comment by AmarokIce** [comment]
It was fixed in 1.5 I guess... If it still exists, I would like to get some more detailed information about the server, thanks!

**Comment by Subilan** [comment]
Thanks for the fix! I truly appreciate your efforts.

I'll put it in game and look into it - when this term of my server ends.

So what is all about TC3? Is it a dependency of your mod or...? I've heard about TC3 causing the problem, but I have no TC3 installed on my server.

Also, if you think the problem is universal and thus can explain similar `"p_130086_" is null` problems, it will be nice if you can provide some explanation here 😇😇😇.

**Comment by AmarokIce** [comment]
A player report it crash with TC3, removing either item will resolve, but I think it my problem  qwq
 `"p_130086_" is null` will occur with `Recipe#getSerializer` is return null, make sure it return a registered `RecipeSerialize<?>`, this step is usually done last back in `Recipe` , so it may be forgotten

**Comment by Subilan** [comment]
Okay I got it. Thank you 😇😇

It's really a tough thing to run a server with numerous unfamiliar mods😅😅 LOL

**Comment by AmarokIce** [comment]
Good luck and have fun!
