### ISSUE TITLE
[Bug] Decode error when joining server with version 1.5 mod

### ISSUE THREAD

**Issue by sandtechnology** [AmarokIce/TskimiSeiranFruitWine#3]
It's a plain for a mobpack to find why player error on join with **no client error and no server error** across 40+ mods, but I manged to write a mod for debugging and found that is your mod mess up the ClientboundUpdateRecipes Packet and causing following error:
![image](https://github.com/AmarokIce/TskimiSeiranFruitWine/assets/20417547/319e2dd7-51c5-4b6b-81d3-a03e92515e31)
debug log:
```
[04:07:35] [Netty Client IO #1/INFO]: ======
[04:07:35] [Netty Client IO #1/INFO]: Res Location1:tksrwine:shaker
[04:07:35] [Netty Client IO #1/INFO]: Res Location2:tksrwine:shake_peach_what
[04:07:35] [Netty Client IO #1/INFO]: ======
[04:07:35] [Netty Client IO #1/INFO]: ======
//Mess up already, should be minecraft
[04:07:35] [Netty Client IO #1/INFO]: Res Location1:craft:crafting_shaped(immersiveengineering:crafting/turret_gun
[04:07:35] [Netty Client IO #1/INFO]: Res Location2:
[04:07:35] [Netty Client IO #1/INFO]: ======
04:07:35] [Netty Client IO #1/ERROR]: Got error when handling packet
io.netty.handler.codec.DecoderException: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: craft:crafting_shaped(immersiveengineering:crafting/turret_gun
```

The problem is your mod don't match the data structure of toNetwork and fromNetwork method, read the extra 4 bytes from the bytebuf on fromNetwork , you can just write it as well to fix it:
https://github.com/AmarokIce/TskimiSeiranFruitWine/blob/9e865b1ece12dd14eb8a8a17915c951e7fb12817/src/main/java/club/someoneice/vine/common/RecipeShaker.java#L135-L151

It's no offense but I personally strongly recommend to just test your mod both **Singleplayer and DedicatedServer** before releasing a new version, it's easy to found such bug on development but very difficult for user and creator since it needs digging that across tens or hundreds mods, which is nightmare.

**Comment by AmarokIce** [comment]
Thanks for report it! and try with 1.6
