### ISSUE TITLE
Some issues need to solved

### ISSUE THREAD

**Issue by ghost** [AmarokIce/TskimiSeiranFruitWine#5]
1.server restarts while there's something processing in the barrel or boiler, you lose whatever was in it. It just disappears. You can right-click on them with bottles, but they don't give you anything in return, the bottles are consumed without giving you anything back.

2.brewing takes entirely too long. I get that it's not exactly a fast process in real life either, but for gameplay purposes it's agonizingly slow. There's also no timer showing you how much longer it's going to take. At first I thought the mod was broken because the progress bar was moving so slowly.
The documentation is... lacking at best. You mention a handful of drinks on the mod's description, but there are a lot more drinks showing up in JEI that you don't talk about. Sake, for example. It shows up in JEI, but I'm assuming it can't actually be made without specifically having Croptopia installed, as the rice from Farmer's Delight isn't dictionaried to work properly. No indication of what the boiler does or how to use it. It let me put water in it, but boiling also requires heat. Do we put a campfire underneath? Do we put the boiler under the barrel? Next to it? On top of it? No idea. There's also no indication that you have to shift-right-click explicitly on the tap in order to get any kind of UI, and even then the UI can't be interacted with (why shift-right-click and not right-click?) Vanilla Minecraft potatoes, raw or baked, also can't be placed in the barrel to make vodka.

3. when that server-restart issue happens, you can't use the barrel anymore. You have to pick it up and then put it back down to "reset" the barrel's status before it will start working again. Same thing happens to the boiler.

**Comment by AmarokIce** [comment]
got it
