### ISSUE TITLE
反馈两个新的漏洞

### ISSUE THREAD

**Issue by ghost** [AmarokIce/TskimiSeiranFruitWine#7]
1.20.1 v1.8在取出蒸馏锅里的酒时，在取完后仍右击会导致游戏闪退（已经因为手快闪退好几次了orz），然后那个桶就没法用了...
用酒瓶从酒桶中取出酒后再右键酒桶会直接导致游戏闪退。

**Comment by AmarokIce** [comment]
收到

**Comment by AmarokIce** [comment]
已在 v1.9 修正
